Entity/Picture.php
<?php

namespace Jcc\Bundle\AlbumBundle\Entity;

use DateTime;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Picture
 *
 * @ORM\Entity(repositoryClass="Jcc\Bundle\AlbumBundle\Service\Picture")
 * @ORM\Table(name="picture")
 */
class Picture
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Folder
     *
     * @ORM\ManyToOne(targetEntity="Folder", inversedBy="pictures")
     * @ORM\JoinColumn(name="folder_id", referencedColumnName="id")
     */
    private $folder;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;

    /**
     * @var string
     *
     * @ORM\Column(name="hash", type="string", length=255)
     */
    private $hash;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="original_date", type="datetime")
     */
    private $originalDate;

    /**
     * @var boolean
     *
     * @ORM\Column(name="resized", type="boolean", nullable=false)
     */
    private $resized = false;


    /**
     * @var array
     *
     * @ORM\ManyToMany(targetEntity="Tag", mappedBy="pictures")
     */
    private $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set folder
     *
     * @param Folder $folder
     *
     * @return Picture
     */
    public function setFolder(Folder $folder)
    {
        $this->folder = $folder;

        return $this;
    }

    /**
     * Get folder
     *
     * @return Folder
     */
    public function getFolder()
    {
        return $this->folder;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Picture
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set hash
     *
     * @param string $hash
     * @return Picture
     */
    public function setHash($hash)
    {
        $this->hash = $hash;

        return $this;
    }

    /**
     * Get hash
     *
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     *
     * @return DateTime
     */
    public function getOriginalDate()
    {
        return $this->originalDate;
    }

    /**
     * @param DateTime $originalDate
     * @return Picture
     */
    public function setOriginalDate(DateTime $originalDate)
    {
        $this->originalDate = $originalDate;

        return $this;
    }
    /**
     *
     * @return boolean
     */
    public function isResized()
    {
        return $this->resized;
    }

    /**
     * @param boolean $resized
     * @return Picture
     */
    public function setResized($resized)
    {
        $this->resized = $resized;

        return $this;
    }

    public function getTags()
    {
        return $this->tags;
    }

    public function setTags($tags)
    {
        $this->tags = $tags;
    }

    public function addTag(Tag $tag) {
        $this->tags[] = $tag;
    }

    public function removeTag(Tag $tag) {
        $this->tags = array_filter($this->tags ?: array(), function($tag){
            return $tag->getHash() == $tag->getHash();
        });
    }

    public function getTagHashes()
    {
        $result = array();
        foreach($this->tags ?: array() as $tag) {
            $result[] = $tag->getHash();
        }

        return $result;
    }
}

Resources/views/Admin/folder.html.twig
{% extends 'JccAlbumBundle:Admin:index.html.twig' %}

{% set title = folder.name %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
        </div>
    </div>

    <div class="row">
    {% for picture in pictures %}
        <div class="pull-left">
            <a class="img-thumbnail" href="{{ path('picture', {'mode' : 'fit', 'width' : '1024', 'height' : '780', 'hash' : picture.hash }) }}"
               data-src="{{ picture.path }}" data-picture="{{ picture.hash }}" data-tags="{{ picture.tagHashes|join(',') }}">
                <img src="{{ path('picture', {'mode' : 'crop', 'width' : '200', 'height' : '200', 'hash' : picture.hash }) }}" class="sz200x200" />
            </a>
        </div>
    {% endfor %}
    </div>

{% endblock %}
{% block slideshow_controls %}
    {% for k,tag in tags %}
        <a class="tag btn btn-default {% if k == 0 %}new-group{% endif %}"
           href="{{ path('admin_tag_picture', {'pic' : 'XXX', 'tag' : tag.hash, 'state' : 'YYY'}) }}"
           title="{{ tag.name }}" data-hash="{{ tag.hash }}">
            <span class="glyphicon glyphicon-{{ tag.class }}"></span>
        </a>
    {% endfor %}
    <a class="download btn btn-warning new-group" data-href="{{ path('download', {'hash' : 'XXX'}) }}" title="Download original file">
         <span class="glyphicon glyphicon-download"></span>
    </a>
{% endblock %}

Resources/views/Admin/index.html.twig
<!DOCTYPE html>
<html>
    <head>
        <title>{{ title|default('Pictures') }}</title>
        <link rel="shortcut icon" href="/assets/images/favicon.png">
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">

        {% stylesheets filter='cssrewrite'
            'assets/highslide-4.1.13/highslide.css'
            'assets/bootstrap-3.0.2/css/bootstrap.min.css'
            'assets/main.css'
            'assets/admin.css'
        %}
        <link href="{{ asset_url }}" rel="stylesheet" media="screen" />
        {% endstylesheets %}

    </head>
    <body >
        <div class="container">
            <h1>{{ title|default('Pictures') }}</h1>
            <div class="row">
                <div class="col-md-3">
                    {{ render(controller("JccAlbumBundle:Admin:sidebar", {path: app.request.attributes.get('path')})) }}
                </div>
                <div class="col-md-9">
                    {% block body %}{% endblock %}
                </div>
            </div>
        </div>
        <div class="slideshow hidden">
            <div class="picture">
                <img src="{{ asset('assets/images/loading.gif') }}">
                <div class="controls-container">
                <div class="controls">
                    <a href="#prev" class="btn btn-primary prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
                    <a href="#next" class="btn btn-success play"><span class="glyphicon glyphicon-play"></span></a>
                    <a href="#next" class="btn btn-primary next"><span class="glyphicon glyphicon-chevron-right"></span></a>
                    {% block slideshow_controls %}{% endblock %}
                    <a href="#close" class="btn btn-danger ssclose new-group"><span class="glyphicon glyphicon-remove"></span></a>
                </div>
                </div>
            </div>
            <div class="hidden">
                <img class="prevloader" src="{{ asset('assets/images/loading.gif') }}">
                <img class="nextloader" src="{{ asset('assets/images/loading.gif') }}">
            </div>
        </div>

        {% javascripts
            'assets/jquery-1.7.1.min.js'
            'assets/bootstrap-3.0.2/js/bootstrap.min.js'
            'assets/hammer.js'
            'assets/main.js'
            'assets/admin.js'
        %}

        <script type="text/javascript" src="{{ asset_url }}"></script>
        {% endjavascripts %}
    </body>
</html>

Resources/views/Admin/sidebar.html.twig
{% set depth = 0 %}
<ul class="nav jca-sidenav">
    <li>
        <a href="{{ path('admin_tags') }}">All tags</a>
    </li>
    {% for folder in folders %}
        <li>
            {% if(folder.depth) > depth %}
            <ul class="nav"><li>
            {% endif %}

            <a href='{{ path('admin_folder', {'path' : folder.path}) }}'>{{ folder.name }}</a>

            {% if(folder.depth) < depth %}
                </li></ul>
            {% endif %}
        </li>
        {% set depth = folder.depth %}
    {% endfor %}
</ul>

Resources/views/Admin/tagEdit.html.twig
{% extends 'JccAlbumBundle:Admin:index.html.twig' %}

{% set title = 'Tag: ' ~ tag.name %}

{% block body %}

    <div class="row">
        {% if tag.id %}
        <div class="col-md-4">
            <a href="{{ path('tag_view', {hash: tag.hash, slug: tag.slug}) }}" class="btn btn-success">
                <span class="glyphicon glyphicon-new-window"></span> Sharing is caring!
            </a>
        </div>
        {% endif %}
        <div class="col-md-8">
            {{ form(form, {action:path('admin_tag_edit', {id:tag.id}) }) }}
        </div>
    </div>

    <div class="row">
    {% for picture in pictures %}
        <div class="pull-left">
            <a class="img-thumbnail" href="{{ path('picture', {'mode' : 'fit', 'width' : '1024', 'height' : '780', 'hash' : picture.hash }) }}"
               data-src="{{ picture.path }}" data-picture="{{ picture.hash }}" data-tags="{{ picture.tagHashes|join(',') }}">
                <img src="{{ path('picture', {'mode' : 'crop', 'width' : '200', 'height' : '200', 'hash' : picture.hash }) }}" class="sz200x200" />
            </a>
        </div>
    {% endfor %}
    </div>

{% endblock %}
{% block slideshow_controls %}
    {% for k,t in tags %}
        <a class="tag btn btn-default {% if k == 0 %}new-group{% endif %}"
           href="{{ path('admin_tag_picture', {'pic' : 'XXX', 'tag' : t.hash, 'state' : 'YYY'}) }}"
           title="{{ t.name }}" data-hash="{{ t.hash }}">
            <span class="glyphicon glyphicon-{{ t.class }}"></span>
        </a>
    {% endfor %}
    <a class="download btn btn-warning new-group" data-href="{{ path('download', {'hash' : 'XXX'}) }}" title="Download original file">
         <span class="glyphicon glyphicon-download"></span>
    </a>
{% endblock %}

Resources/views/Admin/tagList.html.twig
{% extends 'JccAlbumBundle:Admin:index.html.twig' %}

{% set title = 'All tags' %}

{% block body %}
<ul class="nav jca-sidenav">
    <li>
            <a href='{{ path('admin_tag_edit') }}'>
                <span class="glyphicon glyphicon-new"></span>New tag
            </a>
    </li>
    {% for tag in tags %}
        <li>
            <a href='{{ path('admin_tag_edit', {id: tag.id, slug: tag.slug}) }}'>
                <span class="glyphicon glyphicon-{{tag.class}}"></span>{{ tag.name }}</a>
        </li>
    {% else %}
        <li>No tags</li>
    {% endfor %}
</ul>
{% endblock %}